backend:
  name: github
  repo: mwanawasa15/masaiti-2026
  branch: main
  base_url: https://api.netlify.com # This is the magic bridge
  auth_endpoint: auth
  site_domain: lyuumbo-masaiti-2026.pages.dev
  app_id: YOUR_CLIENT_ID_HERE # Paste your actual Client ID here
