backend:
  name: github
  repo: mwanawasa15/masaiti-2026
  branch: main
  # Replace with your actual Client ID from GitHub
  app_id: Ov23lipiRq7scvCAlG4U
  # This tells Decap to look for the "Secret" via a proxy
  base_url: https://api.netlify.com 
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "updates"
    label: "Campaign Updates"
    folder: "updates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
